services:
  - type: web
    name: devport-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    region: oregon
    disk:
      name: devport-data
      mountPath: /data
      sizeGB: 1
